### ISSUE TITLE
3.5inch RPi LCD (B) Waveshare is not working

### ISSUE THREAD

**Issue by haui-btc** [haui-btc/raspiblitz#1]
https://www.pi-shop.ch/3-5inch-rpi-lcd-b-ic-test-board

This LCD doesn't work with preconfigured drivers.

**Comment by haui-btc** [comment]
**Delete preconfigured drivers and install V2 of the LCD35 driver:**
```
sudo rm -rf LCD-show
git clone https://github.com/waveshare/LCD-show
chmod -R 755 LCD-show
cd LCD-show/
sudo ./LCD35-show-V2
```

**Comment by redmac68** [comment]
This worked fine for me, but I had to change the last line to:
sudo bash LCD35B-show-V2

**Comment by redmac68** [comment]
Font is a bit squashed :(
